name: Python CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  python-linter-vulnerability-scanners:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Python Setup
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' 

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install + run flake8
      run: |
        pip install flake8
        flake8 .

    - name: Install + run safety (vulnrabilities)
      run: |
        pip install safety
        with:
          api-key: ${{ secrets.SAFETY_API_KEY }}
        safety scan -r requirements.txt

    - name: Install + run bandit (security)
      run: |
        pip install bandit
        bandit -r .